<!DOCTYPE html>
<html>
<head>
    <title>Success page</title>

    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:wght@400;700&family=Roboto:ital,wght@0,400;1,300&display=swap" rel="stylesheet">
    
    <style>
        h1{
            text-align: center;
            margin-top: 1px;
            font-size: 45px;
        }
        
        body{
            margin: 0;
            color: #333;
	        font-family:'Montserrat', sans-serif;	
            line-height: 1.6; 
        }
        
        img{
            width: 100%;
        }
        
        .boxes{
            margin-top: -10px;
            text-align: center;
        }
    </style>
</head>
<body>
        <h1>Моя квартира</h1>

        <img src="http://dgdesign.ru/uploads/posts/2015-11/1446817830_shapka-sayta-gorod.jpg" alt="">
        
        <div class="boxes">

        <h4>Ваша заявка успешно оформлена!</h4>
        <h4>Ожидайте звонка нашего риэлтора.</h4>
        <form action="/main" method="get">

        <input type="submit" value="На главную"/>
</form>
    </div>
</body>
</html>